### ISSUE TITLE
Add libraries from JdeRobot

### ISSUE THREAD

**Issue by scarrionv** [JdeRobot/Scratch4Robots#4]
Add librarys on wich the proyect depends:
- comm
- JdeRobotTypes
- config

**Comment by raulperula** [comment]
I think we should do purely ROS this package. After that, we could do a second stop implementing a low-level wrapper to manage ICE or ROS msgs. Opinions?

**Comment by jmplaza** [comment]
Yes, this tool will work both with ROS drivers and with ICE drivers. Creating the ROS package is the priority now so we will do some things in the quick (not the best) way, even copying inside some of the dependences (like comm wrapping, config, JdeRobotTypes). We talked about this on last thursday. In the short term we will support ROS through comm wrapper. Later on we will refine it linking to the right external packages and refining the support for ICE drivers. 

The support for ICE is also needed ASAP to work with drones and small educative robots (existing ICE drivers). In the long term we will replace all ICE drivers by ROS ones, so we will even delete the wrapper layer from Scrarch4Robots. But that takes time. We are following the same policy with the VisualStates tool.
